# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
    -   id: black
        language_version: python3.9
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.245'
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
    -   id: mypy
        args: [--config-file=pyproject.toml]
