[project]
name = "lorenzpy"
readme = "README.md"
version = "0.1.0"
authors = [
    { name = "Dennis Duncan", email = "DuncDennis@gmail.com" }
]
license = { file = "LICENSE.txt" }
dependencies = [
    "numpy==1.24.2",
]

[project.optional-dependencies]
dev = [
    "pytest==7.2.0",
    "pytest-cov==4.0",
    "black==22.12.0",
    "mypy==1.1.1",
    "ruff==0.0.254",
]

#[tool.pytest.ini_options]
#addopts = "--cov=lorenzpy"

[tool.black]
target-version = ['py38', 'py39', 'py310', 'py311']
line-length = 88

[tool.mypy]
files = "src/lorenzpy/"

[tool.ruff]
line-length = 88
select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "D",    # pydocstyle
    "I001", # isort
]
src = ["src", "tests"]

[tool.ruff.pydocstyle]
convention = "google"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
