[project]
name = "lorenzpy"
readme = "README.md"
version = "0.1.0"
authors = [
    { name = "Dennis Duncan", email = "DuncDennis@gmail.com" }
]
license = { file = "LICENSE.txt" }
dependencies = [
    "numpy==1.24.2",
]

[project.optional-dependencies]
dev = [
    "pytest==7.2.0",
    "pytest-cov==4.0",
    "black==22.12.0",
    "mypy==0.961",
]

[tool.black]
target-version = ['py39']

[tool.mypy]
python_version = "3.9"
files = "src/lorenzpy/"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
