[project]
name = "lorenzpy"
readme = "README.md"
version = "0.1.0"
authors = [
    { name = "Dennis Duncan", email = "DuncDennis@gmail.com" }
]
license = { file = "LICENSE.txt" }
dependencies = [
    "numpy"
]

[project.optional-dependencies]
dev = [
    "pytest==7.2.0",
    "pytest-cov==4.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
