name: Here1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]
    name: Here Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: confirm pip version
        run: pip --version
      - name: installation
        run: pip install .[dev]
      - name: test
        run: python -m pytest --cov
